name: DigitalStuff
favicon: null
layout_spectrum: 0.7086022382136434
typography_spectrum: 0.13516061403788626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7404347548726946
  lightness: 0.9651326341554523
  saturation: 0.8151201975997537
  rhythmicContrast: 0.760471752146259
purpose: []
